In [5]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

import pickle

In [2]:
data = pd.read_csv('diamonds.csv')

data['cut'] = data['cut'].map({'Ideal':1, 'Premium':2, 'Good':3, 'Very Good':4, 'Fair':5})
data['color'] = data['color'].map({'D':1, 'E':2, 'F':3, 'G':4, 'H':5, 'I':6, 'J':7})
data['clarity'] = data['clarity'].map({'I1':1, 'SI2':2, 'SI1':3, 'VS2':4, 'VS1':5, 'VVS2':6, 'VVS1':7, 'IF':8})

data

       carat  cut  color  clarity  depth  table  price     x     y     z
0       0.23    1      2        2   61.5   55.0    326  3.95  3.98  2.43
1       0.21    2      2        3   59.8   61.0    326  3.89  3.84  2.31
2       0.23    3      2        5   56.9   65.0    327  4.05  4.07  2.31
3       0.29    2      6        4   62.4   58.0    334  4.20  4.23  2.63
4       0.31    3      7        2   63.3   58.0    335  4.34  4.35  2.75
...      ...  ...    ...      ...    ...    ...    ...   ...   ...   ...
49995   0.72    1      1        3   60.8   57.0   2757  5.75  5.76  3.50
49996   0.72    3      1        3   63.1   55.0   2757  5.69  5.75  3.61
49997   0.70    4      1        3   62.8   60.0   2757  5.66  5.68  3.56
49998   0.86    2      5        2   61.0   58.0   2757  6.15  6.12  3.74
49999   0.75    1      1        2   62.2   55.0   2757  5.83  5.87  3.64

[50000 rows x 10 columns]

In [3]:
y = data['price']
X = data.drop(['price','depth','table'], axis=1)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

rf = RandomForestRegressor(random_state=42)
rf.fit(X_train, y_train)

y_pred = rf.predict(X_test)

mae = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
r2 = r2_score(y_test, y_pred)

print(f'MAE\t{mae:.2f}')
print(f'RMSE\t{rmse:.2f}')
print(f'R2\t{r2:.2f}')
print()

single = pd.DataFrame([{'carat':1,
                        'cut':3,
                        'color':3,
                        'clarity':3,
                        'x':3,
                        'y':3,
                        'z':3}])
# single = [[1,3,3,3,3,3,3]]
print(rf.predict(single)[0])

MAE	269.30
RMSE	536.73
R2	0.98

4449.79

In [6]:
with open('diamonds_rf_model.pkl','wb') as f:
    pickle.dump(rf, f)